### ISSUE TITLE
system.base fails to install

### ISSUE THREAD

**Issue by ghost** [solus-project/package-management#5]
when trying to install system.base i get this error:
System error. Program terminated.
[Errno 2] No such file or directory: 'lib'

this also occurs (because of safety switch) when trying to install anything when the basedir does not have system.base.

You can work around it by installing baselayout with --ignore-safety.

steps to reproduce:
tmpd=$(mktemp -d)
sudo eopkg ar a https://packages.solus-project.com/unstable/eopkg-index.xml.xz -D $tmpd
sudo eopkg it -c system.base -D $tmpd

**Comment by ikeydoherty** [comment]
You need to install baselayout in there first.

This is how our ISO script handles it:

```
def init_root():
    ''' Construct run links, etc '''
    try:
        os.makedirs("%s/run/lock" % get_image_root())
        os.makedirs("%s/var" % get_image_root())
        os.symlink("../run/lock", "%s/var/lock" % get_image_root())
        os.symlink("../run", "%s/var/run" % get_image_root())
    except Exception, ex:
        print("Unable to set up links for bootstrap: %s" % ex)
        clean_exit(1)
```

in bashisms:

```
mkdir -p $tmpd/run/lock
mkdir $tmpd/var
ln -sv ../run/lock $tmpd/var/lock
ln -s ../run $tmpd/var/run
```

Then you need to add the repo, and then _first_ install baselayout, to define the filesystem layout going forward, i.e. `sudo eopkg it baselayout --ignore-safety -D $tmpd`

The initial bootstrap is because of a chicken and egg problem, in which eopkg will potentially create the wrong dirs in the target causing breakage later on.

So, why do you need to install Solus into a temporary directory anyway? Got my curiosity going :)

**Comment by ikeydoherty** [comment]
BTW, another _MUST_: you must always use `--ignore-comar` in this version of `eopkg` when installing packages into the root, otherwise it will connect to host dbus and cause changes outside of this root.

So ideally I need to know what you intend to build here so I can advise you better (We may even have your usecase covered already..)

**Comment by ghost** [comment]
I made a (nspawn) container of the minimal to test packages without message up my enviroment, and it is working great. 
Thank you for the --ignore-comar tip, my makefile is pretty much the same as the image creator except i create a polkit user ( but i assume this is a stateless thing). 
Thanks for all you hard work

**Comment by ikeydoherty** [comment]
OK so for the missing users if you need to prebootstrap that

`cp -Rva $tmpd/usr/share/baselayout/* $tmpd/etc/.`

These parts aren't yet stateless hence the bootstrap issue :]
